version: '3'
services:
  composer:
    image: composer:2.1.5
    volumes:
      - ./src:/app
    command: composer install --ignore-platform-reqs
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - mariadb
    depends_on:
      - composer
      - mariadb
    command: "php spark serve --host 0.0.0.0 --port 80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - 8181:80
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=default
      - MYSQL_DATABASE=default